### ISSUE TITLE
Feature request: custom text

### ISSUE THREAD

**Issue by joepio** [badboy/mdbook-open-on-gh#4]
Hi there! Thanks for sharing this :)

I'd like to make some small modifications to the footer, so the only text in the Footer would read `Edit this page on GitHub`.  I think the `Found a bug?` question doesn't fit my usecase, and refering to `file` is maybe a bit less clear then `document`.

Maybe a custom property in the `.toml` file would work for this?

```toml
[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]
footer_text = "Edit this page on GitHub"
```
